### ISSUE TITLE
Ignoring certain prefixes?

### ISSUE THREAD

**Issue by mayani** [johnotander/postcss-remove-prefixes#3]
Is there a way to ignore certain prefixes?

**Use Case**

In my postcss configuration, I run
 
- postcss-unprefix
- postcss-remove-prefixes 
- autoprefixer 

However, certain prefixes like `-webkit-font-smoothing` should not be removed as they have no corresponding un-prefixed version.

**Comment by johno** [comment]
Hey @mayani. There isn't a way to currently ignore certain prefixes, but I definitely think taking an optional array of regex/strings to ignore would be 👌 👍 . I've added it to my todo list for when I can get around to it, but if you wanted to take a stab at a PR that'd be great too!
