### ISSUE TITLE
If I use this plugin do I need to use these three plugins?

### ISSUE THREAD

**Issue by jitendravyas** [johnotander/postcss-remove-prefixes#6]
https://github.com/postcss/autoprefixer#how-to-work-with-legacy--webkit--only-code

**Comment by johno** [comment]
I would recommend running those plugins before `postcss-remove-prefixes` in case your stylesheet is missing the unprefixed declaration. Also, you can note that this plugin likely only needs to be run once per stylesheet/project (assuming you save the output as the new source file).
